version: '3.8'

networks:
  poll: 
  
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    restart: on-failure
    ports:
      - 8088:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./nginx/logs:/var/logs/nginx:rw
    networks:
      - poll
    depends_on:
      - poll
      - poll_db

  poll:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: poll_app
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      - poll_db
    volumes:
      - ./:/var/www/html
    networks:
      - poll

  poll_db:
    image: mysql:latest
    container_name: poll_db
    restart: on-failure
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: poll
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - poll